@startuml SingletonPattern

class ChocolateBoiler {
    +{static} ChocolateBoiler getInstance()
    -{static} ChocolateBoiler singleInstance
    -ChocolateBoilder() // If possible, make the constructor inaccessible.
}

@enduml